config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  #Lineボット
  post '/callback', to:'webhook#callback'
  get '/link',to:'webhook#link'
  get '/redirect_lineaccount',to:'webhook#redirect_lineaccount',as: 'redirect_lineaccount'
  #admin
  get 'admin/index'
  get 'admin/show/:id' => 'admin#show',as:'admin_show'
  get 'admin/attendance/:id' => 'admin#attendance',as:'admin_attendance'
  get 'admin/earning/:id' => 'admin#earning',as:'admin_earning'
  post 'admin/earning_search_month'
  get 'admin/earning_search_month'
  post 'admin/attendance_search_month'
  get 'admin/attendance_search_month'
  post 'admin/search_month'
  get 'admin/search_month'

  #earning
  get 'earning/index/:id' => 'earning#index',as:'earning_index'
  get 'earning/show' => 'earning#show',as:'earning_show'
  post 'earning/earn'

  #attendance
  get 'attendance/index/:id' => 'attendance#index',as:'attendance_index'
  get 'attendance/show/:id' => 'attendance#show',as:'attendance_show'
  post 'attendance/in_time'
  post 'attendance/remote_in_time'
  post 'attendance/out_time'
  post 'attendance/break_in_time'
  post 'attendance/break_out_time'

  #home
  get 'home/index'
  get 'home/search_month'
  post 'home/search_month'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/attendance.html.erb
<h1><%=@employee.username%>の勤怠管理</h1>
<%= form_tag(admin_attendance_search_month_path(id:@employee.id), method: :post) do%>
<%= number_field_tag :year,@year%>年
<%= number_field_tag :month,@month%>月
<%= submit_tag "検索" %>
<%end%>

<h2>勤務詳細</h2>
<div class="row">
  <% @attendances.each do |attendance| %>
  <div class="col-sm-12  col-md-6">
    <div class="card bg-light mb-3">
      <div class="card-header"><%=attendance.in_time.try(:strftime, "%Y年%-m月%-d日(#{%w(日 月 火 水 木 金 土)[attendance.in_time.wday]})")%></div>
      <div class="card-body">

        <div class="row attendance" style="margin-bottom:30px;">
          <div class="col-sm-12 col-md-6 attendance-border">
            <%if attendance.is_remote then%>
            <div class="attendance_title">リモート出勤</div>
            <div class="attendance_time">
              <%=attendance.in_time.try(:strftime, "%H時%M分%S秒")%>
            </div>
            <%else%>
            <div class="attendance_title">出勤</div>
            <div class="attendance_time">
              <%=attendance.in_time.try(:strftime, "%H時%M分%S秒")%>
            </div>
            <%end%>
          </div>
          <div class="col-sm-12 col-md-6 attendance-border">
            <div class="attendance_title">退勤</div>
            <div class="attendance_time">
              <%=attendance.out_time.try(:strftime, "%H時%M分%S秒")%>
            </div>
          </div>
        </div>

         <%if attendance.break.present? then%>

        <h3>休憩まとめ</h3>
        <table class="table table-striped">
          <thead>
            <tr>
              <th scope="col">開始時刻</th>
              <th scope="col">終了時刻</th>
            </tr>
          </thead>
          <tbody>
            <%attendance.break.each do |rest|%>
            <tr>
              <td><%=rest.in_time.try(:strftime, "%H時%M分%S秒")%></td>
              <td><%=rest.out_time.try(:strftime, "%H時%M分%S秒")%></td>
            </tr>
          <%end%>
        </tbody>
        </table>
        <%end%>

        <%if attendance.out_time.nil?%>
        <p>出勤中</p>
        <%else%>

        <h3>合計時間</h3>
        <table class="table table-striped">
          <tbody>
            <tr>
              <th scope="row">休憩</th>
              <td><%=sec_to_jp(sum_break_hour(attendance))%></td>
            </tr>
            <tr>
              <th scope="row">出勤</th>
              <td><%=sec_to_jp(working_hour(attendance))%></td>
            </tr>
            <tr>
              <th scope="row">仕事</th>
              <td><%=sec_to_jp(working_hour(attendance)-sum_break_hour(attendance))%></td>
            </tr>
          </tbody>
        </table>
        <%end%>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/admin/earning.html.erb
<h1><%=@employee.username%>の売り上げ管理</h1>
<%= form_tag(admin_earning_search_month_path(id:@employee.id), method: :post) do%>
<%= number_field_tag :year,@year%>年
<%= number_field_tag :month,@month%>月
<%= submit_tag "検索" %>
<%end%>

<% @earnings.each do |earning| %>
    <p>日程　<%=earning.date.try(:strftime, "%Y年%-m月%-d日(#{%w(日 月 火 水 木 金 土)[earning.date.wday]})")%></p>
    <p>場所　<%=earning.location%></p>
    <p>売り上げ金　<%=earning.revenue%>円</p>
    <br>
<% end %>

app/views/admin/index.html.erb
<h1>管理者ホーム</h1>

<h2>従業員リスト</h2>
<div class="row">
  <% @employees.each do |employee| %>

  <div class="col-sm-12 col-md-6">
    <div class="card img-thumbnail text-center">
      <img class="card-img-top" src="/assets/sample.png" alt="画像" style="max-width:300px; margin:auto;">
      <div class="card-body px-2 py-3">
        <h5 class="card-title"><%=employee.username%></h5>
        <%= link_to "給与まとめ",admin_show_path(id:employee.id),class:"btn btn-primary btn-sm"%>
        <%= link_to "勤怠管理",admin_attendance_path(id:employee.id),class:"btn btn-secondary btn-sm"%><br>
      </div><!-- /.card-body -->
    </div><!-- /.card -->
  </div><!-- /.col-sm-6.col-md-3 -->
  <% end %>
</div><!-- /.row -->

app/views/admin/show.html.erb
<h1><%=@employee.username%>さん<%=%><%=@year%>年<%=@month%>月のまとめ</h1>
<%= form_tag(admin_search_month_path(id:@employee.id), method: :post) do%>
<%= number_field_tag :year,@year%>年
<%= number_field_tag :month,@month%>月
<%= submit_tag "検索" %>
<%end%>

<table class="table table-striped" style="margin-top:50px;">
  <tbody>
    <tr>
      <th scope="row">仕事時間合計</th>
      <td><%=sec_to_jp(sum_working_hour(@attendances))%></td>
    </tr>
    <tr>
      <th scope="row">給与合計</th>
      <td><%=sum_salary(@attendances,@employee).ceil%>円</td>
    </tr>
    <tr>
      <th scope="row">交通費</th>
      <td><%=sum_travel_cost(@attendances,@employee)%>円</td>
    </tr>
    <tr>
      <th scope="row">支払い合計</th>
      <td><%=sum_travel_cost(@attendances,@employee)+sum_salary(@attendances,@employee).ceil%>円</td>
    </tr>
  </tbody>
</table>