config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  #Lineボット
  post '/callback', to:'webhook#callback'
  get '/link',to:'webhook#link'
  get '/redirect_lineaccount',to:'webhook#redirect_lineaccount',as: 'redirect_lineaccount'
  #admin
  get 'admin/index'
  get 'admin/show/:id' => 'admin#show',as:'admin_show'
  get 'admin/attendance/:id' => 'admin#attendance',as:'admin_attendance'
  get 'admin/earning/:id' => 'admin#earning',as:'admin_earning'
  post 'admin/earning_search_month'
  get 'admin/earning_search_month'
  post 'admin/attendance_search_month'
  get 'admin/attendance_search_month'
  post 'admin/search_month'
  get 'admin/search_month'

  #earning
  get 'earning/index/:id' => 'earning#index',as:'earning_index'
  get 'earning/show' => 'earning#show',as:'earning_show'
  post 'earning/earn'

  #attendance
  get 'attendance/index/:id' => 'attendance#index',as:'attendance_index'
  get 'attendance/show/:id' => 'attendance#show',as:'attendance_show'
  post 'attendance/in_time'
  post 'attendance/remote_in_time'
  post 'attendance/out_time'
  post 'attendance/break_in_time'
  post 'attendance/break_out_time'

  #home
  get 'home/index'
  get 'home/search_month'
  post 'home/search_month'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  has_many :break
  scope :date_between, -> from, to {
  if from.present? && to.present?
    where(in_time: from..to)
  elsif from.present?
    where('in_time >= ?', from)
  elsif to.present?
    where('in_time <= ?', to)
  end
}

scope :date_month, -> year, month {
  if year.present? && month.present?
    from = Date.new(year.to_i,month.to_i)
    one_month_later = from>>1
    to=one_month_later
    where(in_time: from..to)
  end
}
end

app/controllers/attendance_controller.rb
class AttendanceController < ApplicationController
  before_action :authenticate_user!
  before_action :authenticate_current_user!
  before_action :set_user, only: [:show, :index,:in_time,:out_time,:remote_in_time,:break_in_time,:break_out_time]
  before_action :set_time, only: [:in_time, :out_time,:remote_in_time,:break_in_time,:break_out_time]
  before_action :set_attendance, only: [:break_in_time,:break_out_time]
  def index
    if @user.attendance.empty? then
      in_time=Time.local(1900,1,1,9,0,0,0)
      out_time=Time.local(1900,1,1,9,0,0,0)
      Attendance.create!(user_id:@user.id,in_time:in_time,out_time:out_time)
    end
  end

  def show
  end

  def in_time
    Attendance.create!(user_id:@user.id,in_time:@time)
    redirect_to attendance_index_path(@user.id)
  end

  def remote_in_time
    Attendance.create!(user_id:@user.id,in_time:@time,is_remote:true)
    redirect_to attendance_index_path(@user.id)
  end

  def out_time
    Attendance.where(user_id:@user.id).last.update!(out_time:@time,content:params[:content])
    redirect_to attendance_index_path(@user.id)
  end

  def break_in_time
    Break.create!(user_id:@user.id,attendance_id:@attendance.id,in_time:@time)
    redirect_to attendance_index_path(@user.id)
  end

  def break_out_time
    Break.where(user_id:@user.id,attendance_id:@attendance.id).last.update!(out_time:@time)
    redirect_to attendance_index_path(@user.id)
  end

  private
  def set_user
    @user = User.find(params[:id])
  end
  def set_time
    @time=Time.now+9*60*60
  end
  def authenticate_current_user!
    if current_user.id!=params[:id].to_i then
      redirect_to home_index_path
    end
  end
  def set_attendance
    @attendance=Attendance.where(user_id:@user.id).last
  end

end

app/helpers/attendance_helper.rb
module AttendanceHelper
  def is_working(user)
    if Attendance.find_by(user_id:user.id).present? then
      last_attendance=Attendance.where(user_id:user.id).last
      if last_attendance.out_time.nil? then
        return true
      end
    end
  end

  def is_break(user)
    if Break.find_by(user_id:user.id).present? then
      last_break=Break.where(user_id:user.id).last
      if last_break.in_time.present? && last_break.out_time.nil? then
        return true
      end
    end
  end

  def is_remote(user)
    if Attendance.find_by(user_id:user.id).present? then
      last_attendance=Attendance.where(user_id:user.id).last
        return last_attendance.is_remote
    end
  end
end

app/views/attendance/index.html.erb
<h1>勤怠</h1>

<%if is_working(@user) then%>
  <%if is_break(@user) then%>
    <%= button_to "休憩終了",attendance_break_out_time_path(id:current_user.id), method: :post,class:"btn btn-success attendance_btn" %>
  <%else%>
  <%= form_tag(attendance_out_time_path(id:current_user.id), method: :post) do %>
  <!-- ここにform_tagメソッドを記述 -->
  <p>作業内容</p>
  <%= text_area_tag :content ,"",:id => "content_field",class:"form-control"%>
  <%= submit_tag "退勤" , :id => "out_time_btn" ,:disabled => "true",class:"btn btn-dark attendance_btn"%>
  <% end %>
    <%= button_to "休憩開始",attendance_break_in_time_path(id:current_user.id),method: :post,class:"btn btn-success attendance_btn" %>
  <%end%>
<%else%>
<div class="row">
  <%= button_to "出勤",attendance_in_time_path(id:current_user.id), method: :post,class:"btn btn-dark attendance_btn" %>
  <%= button_to "リモート出勤",attendance_remote_in_time_path(id:current_user.id),method: :post,class:"btn btn-dark attendance_btn" %>
</div>
<%end%>
<script>

  document.getElementById("out_time_btn").onclick = function() {
      var in_time = '<%=@user.attendance.last.in_time-Time.local(2019,1,1,9,0,0,0)%>';
      var jikan= new Date();
      var kijun= new Date('2019/01/01 00:00:00');
      var out_time = (jikan-kijun)/1000
      var break_time = '<%=sum_break_hour(@user.attendance.last)%>'
      var working = (out_time-in_time-break_time)/3600;
      var hourly_wage = "<%=@user.hourly_wage%>";
      var salary = Number(hourly_wage)*working;
  // ここに#buttonをクリックしたら発生させる処理を記述する
  // 「OK」時の処理開始 ＋ 確認ダイアログの表示
if(window.confirm('<%=@user.username%>さんの今日の給与は'+Math.ceil(salary)+'円です。対価に見合っていますか？')){
  window.alert('この調子！'); // example_confirm.html へジャンプ
}
// 「OK」時の処理終了
// 「キャンセル」時の処理開始
else{
  window.alert('次頑張ろう！'); // 警告ダイアログを表示

}
// 「キャンセル」時の処理終了
  };
    document.getElementById("content_field").addEventListener('keyup',function(){
      if (document.getElementById("content_field").value.length > 0) {
        document.getElementById("out_time_btn").disabled = false;
      } else {
        document.getElementById("out_time_btn").disabled = true;
      }
    });
</script>

app/views/attendance/show.html.erb
<h1>Attendance#show</h1>
<p>Find me in app/views/attendance/show.html.erb</p>