config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  #Lineボット
  post '/callback', to:'webhook#callback'
  get '/link',to:'webhook#link'
  get '/redirect_lineaccount',to:'webhook#redirect_lineaccount',as: 'redirect_lineaccount'
  #admin
  get 'admin/index'
  get 'admin/show/:id' => 'admin#show',as:'admin_show'
  get 'admin/attendance/:id' => 'admin#attendance',as:'admin_attendance'
  get 'admin/earning/:id' => 'admin#earning',as:'admin_earning'
  post 'admin/earning_search_month'
  get 'admin/earning_search_month'
  post 'admin/attendance_search_month'
  get 'admin/attendance_search_month'
  post 'admin/search_month'
  get 'admin/search_month'

  #earning
  get 'earning/index/:id' => 'earning#index',as:'earning_index'
  get 'earning/show' => 'earning#show',as:'earning_show'
  post 'earning/earn'

  #attendance
  get 'attendance/index/:id' => 'attendance#index',as:'attendance_index'
  get 'attendance/show/:id' => 'attendance#show',as:'attendance_show'
  post 'attendance/in_time'
  post 'attendance/remote_in_time'
  post 'attendance/out_time'
  post 'attendance/break_in_time'
  post 'attendance/break_out_time'

  #home
  get 'home/index'
  get 'home/search_month'
  post 'home/search_month'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kinchan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body style="padding-top:4.5rem;">
    <header>
      <% if user_signed_in? %>
      <nav class="navbar navbar-expand-lg  navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="/">Kinchan</a>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="ナビゲーションの切替">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <div class="navbar-nav">
      <p style="color:white;margin:10px 20px 0 20px">ようこそ<%=current_user.username%>さん</p>
      <div class="nav-item nav-link logout_btn"><%= link_to "ホーム",home_index_path(current_user.id),class:"logout_btn" %></div>
      <div class="nav-item nav-link logout_btn"> <%= link_to "勤怠入力",attendance_index_path(current_user.id),class:"logout_btn" %> </div>
      <div class="nav-item nav-link logout_btn"><%= link_to 'ログアウト', destroy_user_session_path, method: :delete,class:"logout_btn" %></a>
    </div>
  </div>
  <% end %>
    </header>
        <p class="alert-info"><%= notice %></p>
        <p class="alert-info"><%= alert %></p>
        <div class="container">
    <%= yield %>
    </div>
  </body>
</html>